### ISSUE TITLE
Usage on elixir 1.6.1 on Ubuntu 16.04

### ISSUE THREAD

**Issue by kele6ra** [gertjana/ocpp16-backend#1]
When I try to use the image it throw a lot of warnings, some of them:

> warning: the variable "count_bind" is unsafe as it has been set inside one of: case, cond, receive, if, and, or, &&, ||. Please explicitly return the variable value instead. 

> function :sbroker.async_ask_r/3 is undefined (module :sbroker is not available)

> variable "self" does not exist and is being expanded to "self()", please use parentheses to remove the ambiguity or change the variable name

But it makes the image. When I try to exec it, I am getting the error:
[info]  Application ocpp_backend exited: OcppBackend.start(:normal, []) returned an error: shutdown: failed to start child: OcppBackend.Repo
    ** (EXIT) an exception was raised:
        ** (UndefinedFunctionError) function OcppBackend.Repo.start_link/0 is undefined (module OcppBackend.Repo is not available)
            OcppBackend.Repo.start_link()
            (stdlib) supervisor.erl:365: :supervisor.do_start_child/2
            (stdlib) supervisor.erl:348: :supervisor.start_children/3
            (stdlib) supervisor.erl:314: :supervisor.init_children/2
            (stdlib) gen_server.erl:365: :gen_server.init_it/2
            (stdlib) gen_server.erl:333: :gen_server.init_it/6
            (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
** (Mix) Could not start application ocpp_backend: OcppBackend.start(:normal, []) returned an error: shutdown: failed to start child: OcppBackend.Repo
    ** (EXIT) an exception was raised:
        ** (UndefinedFunctionError) function OcppBackend.Repo.start_link/0 is undefined (module OcppBackend.Repo is not available)
            OcppBackend.Repo.start_link()
            (stdlib) supervisor.erl:365: :supervisor.do_start_child/2
            (stdlib) supervisor.erl:348: :supervisor.start_children/3
            (stdlib) supervisor.erl:314: :supervisor.init_children/2
            (stdlib) gen_server.erl:365: :gen_server.init_it/2
            (stdlib) gen_server.erl:333: :gen_server.init_it/6
            (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3

**Comment by gertjana** [comment]
Hi kele6ra, 

Thanks for trying this out, you should realize that this is just a hobby project for me and nowhere ready to be used in any kind of production environment

The `failed to start child: OcppBackend.Repo` is probably because you don't have a postgres database running or configured correctly, or you didn't ran the ecto migrations

You're welcome to contribute if you find any bugs

**Comment by kele6ra** [comment]
Yes, I understand that it is not a business project. I just want to show that there is a problem with elexir version. Could you say what version did you use to build it? And could you, please, tell me how should I configure the postgresql?

**Comment by kele6ra** [comment]
I found that in config file there is a file with 0cpp.backend.Repo function, but not ocpp.backend. Is it right?

**Comment by gertjana** [comment]
I'm using elixir 1.5.3 currently
about the database configuration, have a look at `config/config.exs` and I suggest reading the Ecto documentation

**Comment by kele6ra** [comment]
Sorry, I am working with elixir and ecto for the first time, could you help me with migrations. I can write full guide of installation after after I run it.

**Comment by gertjana** [comment]
like I said this is a personal project, nowhere ready to be used in the field. 
that said I'm looking forward to your contributions after you learned elixir and ecto
