### ISSUE TITLE
Ecto Migration Problem

### ISSUE THREAD

**Issue by sebastiangrebe** [gertjana/ocpp16-backend#2]
I have just tried your project and am very interested in it.

I have tried starting it as stated but failed with migrating the Ecto repos with Elixir in the following version numbers on Mac: `Erlang/OTP 21 [erts-10.2.3] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe] [dtrace] IEx 1.8.1 (compiled with Erlang/OTP 21)`

From my point of view you have to define the `ecto_repos` property in your `config/config.exs` file otherwise it fails with this error message:

```
warning: could not find Ecto repos in any of the apps: [:ocpp_backend].

You can avoid this warning by passing the -r flag or by setting the
repositories managed by those applications in your config/config.exs:

    config :ocpp_backend, ecto_repos: [...]
```

The final file would look like this:

```
use Mix.Config

config :ocpp_backend,
  ecto_repos: [OcppBackendRepo]

import_config "#{Mix.env}.exs"

```

Afterwards I was able to launch it successfully.

**Comment by gertjana** [comment]
Thanks for your interest, I've updated the code. (I was just running it with the -r flag)
Please note that this is nowhere near 'production ready' code

**Comment by sebastiangrebe** [comment]
I know, just thought it would be helpful.
Are you interested in getting it production ready at sometime and would need some help with it?
